import {chromium} from 'playwright';
import {mkdir,readFile,writeFile,readdir} from 'node:fs/promises';
import assert from 'node:assert/strict';
import {serve} from './server.mjs';
const site=await serve('dist');const browser=await chromium.launch({args:['--no-sandbox']});
const report={pages:[],errors:[],externalRequests:[],interactions:[]};await mkdir('docs/revisao',{recursive:true});
try{const page=await browser.newPage({reducedMotion:'reduce'});page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(m.type()==='error'||m.type()==='warning')report.errors.push(m.text())});page.on('response',r=>{if(r.status()>=400)report.errors.push(`${r.status()} ${r.url()}`)});page.on('request',r=>{if(!r.url().startsWith(site.url)&&!r.url().startsWith('data:'))report.externalRequests.push(r.url())});
for(const width of [1920,1440,1024,768,430,390]){await page.setViewportSize({width,height:1000});for(const route of ['/','/atlas','/domus','/vemka','/ordian']){await page.goto(site.url+route);await page.evaluate(()=>document.fonts.ready);const result=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,badImages:[...document.images].filter(i=>!i.complete||i.naturalWidth===0).map(i=>i.src),missingAnchors:[...document.querySelectorAll('a[href^="#"]')].filter(a=>!document.getElementById(a.getAttribute('href').slice(1))).map(a=>a.getAttribute('href')),title:document.title,forbidden:/simgep/i.test(document.body.innerText),font:document.fonts.check('16px "Instrument Serif"')&&document.fonts.check('16px Manrope')}));report.pages.push({width,route,...result});assert(!result.overflow,`Overflow ${width} ${route}`);assert(!result.forbidden);assert(result.font);assert.equal(result.badImages.length,0);assert.equal(result.missingAnchors.length,0);if(width===1440||width===390)await page.screenshot({path:`docs/revisao/web-${width}-${route.slice(1)||'home'}.png`,fullPage:true});if(route!=='/'){for(let i=0;i<3;i++){await page.getByRole('tab').nth(i).click();await page.getByRole('tabpanel').waitFor();assert(await page.getByRole('tab').nth(i).getAttribute('aria-selected')==='true');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`Tab overflow ${width} ${route} ${i}`)}}}}
await page.setViewportSize({width:1440,height:1000});await page.goto(site.url+'/atlas');await page.getByLabel('Buscar pessoa na demonstração').fill('Clara');assert.equal(await page.locator('#demo-panel .mock-tr:not(.table-head)').count(),1);await page.getByLabel('Buscar pessoa na demonstração').fill('não existe');assert(await page.getByText('Nenhum resultado nesta seleção.').isVisible());report.interactions.push('Busca local Atlas: resultado e estado vazio');
await page.goto(site.url+'/vemka');await page.getByRole('button',{name:'Iniciar atendimento',exact:true}).click();await page.getByRole('button',{name:'Concluir atendimento',exact:true}).click();assert(await page.getByText('ATENDIMENTO CONCLUÍDO',{exact:true}).isVisible());await page.getByRole('button',{name:'Reiniciar demonstração'}).click();report.interactions.push('VemKa: iniciar, concluir e reiniciar');
await page.goto(site.url+'/ordian');await page.getByRole('tab').nth(1).click();await page.getByRole('checkbox',{name:'Validar com a equipe'}).check();assert(await page.getByText('Etapas concluídas na demonstração.').isVisible());report.interactions.push('Ordian: conclusão de tarefa');
await page.locator('.resource button').nth(1).click();assert.equal(await page.locator('.resource button').nth(1).getAttribute('aria-expanded'),'true');await page.locator('.resource button').nth(1).click();assert.equal(await page.locator('.resource button').nth(1).getAttribute('aria-expanded'),'false');report.interactions.push('Recursos: abrir e fechar');
await page.setViewportSize({width:390,height:844});await page.goto(site.url);await page.getByRole('button',{name:'Abrir menu'}).click();await page.locator('#main-nav').getByRole('link',{name:'Domus',exact:true}).click();assert.equal(new URL(page.url()).pathname,'/domus');await page.goBack();assert.equal(new URL(page.url()).pathname,'/');report.interactions.push('Menu móvel, navegação e voltar');
const download=await page.request.get(site.url+'/Portfolio-Atlas-Domus-VemKa-Ordian.pdf');assert(download.ok());assert((await download.body()).subarray(0,4).toString()==='%PDF');report.interactions.push('Download do PDF válido');
await page.goto(site.url+'/nao-existe');assert(await page.getByText('Volte à coleção.').isVisible());
const scan=async(dir)=>{for(const e of await readdir(dir,{withFileTypes:true})){const p=dir+'/'+e.name;if(e.isDirectory())await scan(p);else if(/\.(js|css|html|svg|json)$/.test(e.name)){assert(!/simgep/i.test(await readFile(p,'utf8')),'Nome legado no material público: '+p)}}};await scan('dist');
assert.equal(report.errors.length,0,JSON.stringify(report.errors));assert.equal(report.externalRequests.length,0,'Requisições externas inesperadas');report.result='APROVADO';console.log(`Verificação aprovada: ${report.pages.length} combinações de página/largura, 72 alternâncias de telas, interações, PDF, fontes locais e zero requisições externas.`);
}finally{await writeFile('docs/revisao/website.json',JSON.stringify(report,null,2));await browser.close();await site.close()}
